'use strict';
// ══════════════════════════════════════════
// SFW_ACCIONES — datos de acciones SFW
// Extraído de interactions.js para reducir su tamaño.
// ══════════════════════════════════════════

const SFW_ACCIONES = {
 abrazar: {
 emoji:'', nekos:'hug',
 mencion: [
'abrazó a *@dest* con toda su fuerza',
'corrió hacia *@dest* y no lo/la soltó',
'le dio el abrazo más apretado del universo a *@dest*',
'envolvió a *@dest* en un abrazo de oso',
'se colgó del cuello de *@dest* sin pedir permiso',
 ],
 solo: [
'quiere abrazar a alguien del grupo',
'tiene los brazos abiertos esperando un abrazo',
'anda buscando a quién abrazar desesperadamente',
'necesita un abrazo urgente, ¿quién se apunta?',
'se abrazó a sí mismo/a porque nadie más quiso',
 ],
 },
 hug: {
 emoji:'', nekos:'hug',
 mencion: [
'abrazó a *@dest* sin avisar',
'se lanzó encima de *@dest* a abrazar',
'aplastó a *@dest* con un abrazo enorme',
'no quiere soltar a *@dest* del abrazo',
'le dio un abrazo tan fuerte que *@dest* casi no puede respirar',
 ],
 solo: [
'anda repartiendo abrazos gratis',
'quiere abrazar a alguien del chat',
'tiene los brazos listos para abrazar',
'se siente solo/a y quiere un abrazo',
'busca a alguien cálido con quien abrazarse',
 ],
 },
 besar: {
 emoji:'', nekos:'kiss',
 mencion: [
'besó a *@dest* en los labios sin pedir permiso',
'le robó un beso a *@dest*',
'se lanzó de cabeza a besar a *@dest*',
'plantó un beso enorme en la boca de *@dest*',
'besó a *@dest* apasionadamente',
 ],
 solo: [
'lanzó un beso al aire esperando que alguien lo atrape',
'anda repartiendo besos gratis en el chat',
'quiere besar a alguien del grupo',
'tiene los labios listos para quien quiera',
'manda un beso volado a todo el grupo',
 ],
 },
 kiss: {
 emoji:'', nekos:'kiss',
 mencion: [
'besó a *@dest* de sopetón',
'le dio un beso que dejó sin palabras a *@dest*',
'se acercó sigilosamente y besó a *@dest*',
'le robó los labios a *@dest*',
'besó a *@dest* como si no hubiera un mañana',
 ],
 solo: [
'lanzó un beso al vacío',
'anda buscando unos labios a quien besar',
'quiere dar un beso a alguien del chat',
'tiene ganas de besar a alguien urgentemente',
'manda kisses a todo el que quiera recibirlos',
 ],
 },
 muak: {
 emoji:'', nekos:'kiss',
 mencion: [
'¡MUAK! le dio un beso sonoro a *@dest*',
'se lanzó sobre *@dest* y le estampó un besote',
'le dio el muak más ruidoso del chat a *@dest*',
'besó a *@dest* haciendo el mayor ruido posible',
'¡Muak! le robó un beso a *@dest* sin avisar',
 ],
 solo: [
'¡Muak! manda besos a todo el grupo',
'reparte muaks sin discriminar a nadie',
'manda el besito más ruidoso del universo',
'lanza muaks al aire para quien los atrape',
'¡MUAK! para todo el que quiera uno',
 ],
 },
 kisscheek: {
 emoji:'', nekos:'kiss',
 mencion: [
'le dio un beso tímido en la mejilla a *@dest*',
'se acercó a *@dest* y le plantó un besito en la mejilla',
'le regaló el besito más dulce en la mejilla a *@dest*',
'se puso de puntillas para besar la mejilla de *@dest*',
'le estampó un beso suave en la mejilla a *@dest*',
 ],
 solo: [
'manda besitos en la mejilla a todo el grupo',
'anda dando besitos en la mejilla a quien quiera',
'tiene ganas de dar un besito inocente a alguien',
'lanza un besito al aire para quien lo necesite',
'quiere dar un beso en la mejilla a alguien del chat',
 ],
 },
 beso: {
 emoji:'', nekos:'kiss',
 mencion: [
'le plantó un beso en la mejilla a *@dest*',
'le regaló un besito suave en la mejilla a *@dest*',
'se sonrojó y le dio un beso en la mejilla a *@dest*',
'tímidamente le besó la mejilla a *@dest*',
'le dejó una marca de labios en la mejilla a *@dest*',
 ],
 solo: [
'manda besos al aire para quien quiera recibirlos',
'anda repartiendo besos en la mejilla sin cobrar',
'quiere dar un besito a alguien del grupo',
'lanza un beso tímido al chat',
'tiene ganas de besar a alguien en la mejilla',
 ],
 },
 golpear: {
 emoji:'', nekos:'slap',
 mencion: [
'golpeó a *@dest* sin piedad',
'le dio una bofetada épica a *@dest*',
'abofeteó a *@dest* con toda su alma',
'le cruzó la cara a *@dest* de un guantazo',
'le pegó una cachetada que se escuchó en todo el chat a *@dest*',
 ],
 solo: [
'golpeó al aire con toda su frustración',
'anda buscando a quién darle una bofetada',
'practica sus bofetadas contra el viento',
'tiene la mano lista para quien la quiera sentir',
'está de mal humor y necesita golpear algo',
 ],
 },
 slap: {
 emoji:'', nekos:'slap',
 mencion: [
'le metió un slap a *@dest* sin contemplaciones',
'abofeteó a *@dest* con toda la fuerza',
'le cruzó la cara a *@dest* de un tortazo',
'le pegó una bofetada que retumbó en el chat a *@dest*',
'slapeó a *@dest* sin previo aviso',
 ],
 solo: [
'slapea el aire porque necesita desahogarse',
'anda buscando una cara donde estampar una bofetada',
'golpeó el aire con entusiasmo',
'practica sus bofetadas en el vacío',
'tiene las manos calientes y nadie a quien golpear',
 ],
 },
 acariciar: {
 emoji:'', nekos:'pat',
 mencion: [
'acarició la cabeza de *@dest* con mucha ternura',
'le dio palmaditas suaves en la cabeza a *@dest*',
'acarició el pelo de *@dest* con cariño',
'le hizo mimos en la cabeza a *@dest*',
'consintió a *@dest* con unas caricias muy tiernas',
 ],
 solo: [
'quiere acariciar a alguien del grupo',
'anda buscando a quién darle palmaditas en la cabeza',
'tiene ganas de consentir a alguien con mimos',
'acarició el aire porque no hay nadie cerca',
'reparte caricias gratis para quien las necesite',
 ],
 },
 pat: {
 emoji:'', nekos:'pat',
 mencion: [
'le dio un pat cariñoso a *@dest*',
'pateo a *@dest* en la cabeza con mucho amor',
'le regaló el pat más tierno a *@dest*',
'acarició suavemente la cabeza de *@dest*',
'mimó a *@dest* con pats interminables',
 ],
 solo: [
'anda dando pats gratis a quien los quiera',
'quiere patear a alguien en la cabeza con cariño',
'tiene ganas de hacer mimos a alguien del chat',
'reparte pats de calidad sin cobrar',
'se hizo pats a sí mismo/a porque nadie más apareció',
 ],
 },
 bailar: {
 emoji:'', nekos:'dance',
 mencion: [
'bailó con *@dest* sin parar',
'invitó a *@dest* a la pista de baile',
'sacó a *@dest* a bailar de la nada',
'se puso a bailar con *@dest* sin ningún motivo',
'no quiso dejar de bailar con *@dest* en toda la noche',
 ],
 solo: [
'bailó solo/a como si nadie mirara',
'se puso a bailar en pleno chat sin avisar',
'empezó a moverse al ritmo sin música',
'bailó sin parar aunque estuviera solo/a',
'se marcó unos pasos de baile épicos en solitario',
 ],
 },
 dance: {
 emoji:'', nekos:'dance',
 mencion: [
'hizo bailar a *@dest* sin que pudiera negarse',
'arrancó a bailar junto a *@dest*',
'tomó de la mano a *@dest* y lo/la llevó a bailar',
'se puso a bailar pegado/a a *@dest*',
'convirtió a *@dest* en su pareja de baile',
 ],
 solo: [
'se soltó a bailar en el chat',
'está bailando sin música y sin vergüenza',
'baila como si nadie lo/la estuviera viendo',
'se marcó un solo de baile épico',
'puso su canción favorita en la cabeza y se puso a bailar',
 ],
 },
 llorar: {
 emoji:'', nekos:'cry',
 mencion: [
'lloró en el hombro de *@dest*',
'usó a *@dest* de pañuelo humano',
'se puso a llorar delante de *@dest* sin pudor',
'buscó el consuelo de *@dest* entre lágrimas',
'empapó la camisa de *@dest* de tanto llorar',
 ],
 solo: [
'llora desconsolado/a en el chat',
'se puso a llorar sin ningún motivo aparente',
'está en un rincón llorando a moco tendido',
'llora hasta que alguien le haga caso',
'anda llorando por el chat, alguien que lo/la consuele',
 ],
 },
 cry: {
 emoji:'', nekos:'cry',
 mencion: [
'llora mientras abraza a *@dest*',
'dejó a *@dest* con la camisa mojada de lágrimas',
'corrió hacia *@dest* llorando sin control',
'se puso a llorar mirando a *@dest*',
'no puede parar de llorar junto a *@dest*',
 ],
 solo: [
'está llorando en el chat y no se sabe por qué',
'llora en silencio en un rincón',
'se le cayó el lagrimón más grande del chat',
'llora hasta que alguien le dé un abrazo',
'está soltando el llanto sin control',
 ],
 },
 morder: {
 emoji:'', nekos:'bite',
 mencion: [
'mordió a *@dest* sin previo aviso',
'le clavó los dientes a *@dest* de repente',
'mordió el hombro de *@dest* con ganas',
'decidió morder a *@dest* porque sí',
'dejó marca de mordida en *@dest*',
 ],
 solo: [
'muerde el aire porque tiene ganas de morder a alguien',
'anda buscando a quién hincarle el diente',
'tiene ganas de morder a alguien del grupo',
'muerde cosas al azar por el chat',
'está en modo vampiro y busca su próxima víctima',
 ],
 },
 bite: {
 emoji:'', nekos:'bite',
 mencion: [
'biteó a *@dest* sin contemplaciones',
'le clavó los dientes en el cuello a *@dest*',
'mordió a *@dest* con toda su fuerza',
'atacó el brazo de *@dest* con los dientes',
'le pegó un mordisco enorme a *@dest*',
 ],
 solo: [
'está mordiendo el aire desesperadamente',
'anda en modo fiera buscando a quién morder',
'quiere hincarle el diente a alguien del chat',
'muerde lo que encuentra porque está aburrido/a',
'busca una víctima para morderla sin piedad',
 ],
 },
 sonrojar: {
 emoji:'', nekos:'blush',
 mencion: [
'se sonrojó por culpa de *@dest*',
'se puso rojo/a como un tomate mirando a *@dest*',
'casi le explota la cara de vergüenza por *@dest*',
'no puede evitar sonrojarse ante *@dest*',
'se quedó colorado/a por algo que dijo *@dest*',
 ],
 solo: [
'se sonrojó sin motivo aparente',
'se puso colorado/a de la nada',
'está todo/a sonrojado/a y no quiere decir por qué',
'se pone rojo/a con solo leer el chat',
'le subieron los colores sin razón',
 ],
 },
 blush: {
 emoji:'', nekos:'blush',
 mencion: [
'blushea sin control por culpa de *@dest*',
'se puso rojo/a de cabeza a pies mirando a *@dest*',
'casi se desmaya del blushing que le provocó *@dest*',
'se esconde la cara por lo que le hizo *@dest*',
'no puede mirar a *@dest* a los ojos de tanta vergüenza',
 ],
 solo: [
'está blushando en el chat sin razón aparente',
'se puso colorad@ de repente',
'anda todo/a rojo/a y dice que no es nada',
'blushea solo de existir',
'tiene las mejillas rojas y no quiere explicar por qué',
 ],
 },
 acurrucar: {
 emoji:'', nekos:'cuddle',
 mencion: [
'se acurrucó con *@dest* bajo una manta cálida',
'se pegó a *@dest* como un koala',
'se acurrucó contra *@dest* buscando calor',
'no quiere soltarse de *@dest* en ningún momento',
'se hizo bolita al lado de *@dest* muy contento/a',
 ],
 solo: [
'se acurrucó solo/a en un rincón del chat',
'busca a alguien con quien acurrucarse urgentemente',
'quiere acurrucarse con alguien del grupo',
'anda buscando calor humano desesperadamente',
'se hizo una bolita y espera a que alguien lo/la acompañe',
 ],
 },
 cuddle: {
 emoji:'', nekos:'cuddle',
 mencion: [
'cuddleó a *@dest* sin soltarle',
'se apretujó contra *@dest* buscando mimos',
'se enroscó alrededor de *@dest* como un gatito',
'se acurrucó en los brazos de *@dest* felizmente',
'no hay manera de separar a *@dest* de sus brazos',
 ],
 solo: [
'quiere cuddlear con alguien del grupo',
'anda buscando a alguien con quien hacerse bolita',
'se acurrucó solo/a esperando compañía',
'necesita cuddlear con urgencia, ¿quién se apunta?',
'se abrazó a una almohada imaginaria en el chat',
 ],
 },
 picar: {
 emoji:'', nekos:'poke',
 mencion: [
'picó a *@dest* con el dedo repetidamente',
'le metió el dedo en la costilla a *@dest*',
'no dejó de picar a *@dest* hasta que reaccionó',
'tocó a *@dest* para llamar su atención',
'poke poke poke a *@dest* sin parar',
 ],
 solo: [
'pica al aire porque no hay nadie a quien molestar',
'anda picando a quien se le acerque',
'quiere picar a alguien del grupo',
'tiene el dedo listo para picar a cualquiera',
'anda con el modo poke activado en el chat',
 ],
 },
 poke: {
 emoji:'', nekos:'poke',
 mencion: [
'pokeó a *@dest* sin descanso',
'no para de tocarle el hombro a *@dest*',
'poke poke a *@dest* hasta que haga caso',
'le clavó el dedo a *@dest* para llamarle la atención',
'molestó a *@dest* a pura fuerza de pokes',
 ],
 solo: [
'pokea el aire buscando a quién molestar',
'anda en modo poke y nadie está a salvo',
'quiere pokear a alguien del chat',
'tiene el dedo ansioso y nadie cerca a quien picar',
'poke poke al vacío porque se aburre',
 ],
 },
 punetazo: {
 emoji:'', nekos:'punch',
 mencion: [
'le pegó un puñetazo a *@dest*',
'le mandó un derechazo a *@dest* sin avisar',
'le dio un puñete a *@dest* con toda su fuerza',
'golpeó a *@dest* en la cara sin dudarlo',
'le plantó el puño en la cara a *@dest*',
 ],
 solo: [
'lanzó un puñetazo al aire con rabia',
'anda buscando a quién meter un puñete',
'practica sus golpes en el viento',
'tiene el puño listo para quien se acerque',
'golpeó el aire hasta cansarse',
 ],
 },
 punch: {
 emoji:'', nekos:'punch',
 mencion: [
'punched a *@dest* directo en el estómago',
'le dio un uppercut a *@dest*',
'le metió un combo entero a *@dest*',
'golpeó a *@dest* con un derechazo limpio',
'noqueó a *@dest* de un solo puñetazo',
 ],
 solo: [
'practica sus puñetazos en el vacío',
'anda repartiendo puñetes al aire',
'lanza golpes al viento por no tener a quién pegarle',
'tiene los puños calientes y nadie enfrente',
'golpea el aire hasta que le duela el brazo',
 ],
 },
 reir: {
 emoji:'', nekos:'laugh',
 mencion: [
'se ríe a carcajadas de *@dest*',
'no puede parar de reírse mirando a *@dest*',
'se parte el estómago de risa por culpa de *@dest*',
'se muere de risa por lo que hizo *@dest*',
'llora de risa por culpa de *@dest*',
 ],
 solo: [
'se ríe solo/a sin motivo aparente',
'está muerto/a de risa en el chat',
'no puede parar de reírse de nada',
'se parte de risa por algo que solo él/ella entiende',
'llora de risa y nadie sabe por qué',
 ],
 },
 laugh: {
 emoji:'', nekos:'laugh',
 mencion: [
'se carcajea sin parar de *@dest*',
'se muere de risa mirando a *@dest*',
'no puede aguantar la risa con *@dest* cerca',
'se ríe tanto de *@dest* que le duele la barriga',
'llora de la risa por lo que hizo *@dest*',
 ],
 solo: [
'se carcajea solo/a en el chat',
'está en modo risa y no puede parar',
'ríe sin control y sin explicación',
'se está riendo a mandíbula batiente',
'le dio el ataque de risa y nadie lo/la entiende',
 ],
 },
 correr: {
 emoji:'', nekos:'run',
 mencion: [
'salió corriendo junto a *@dest*',
'echó a correr al lado de *@dest* sin parar',
'se fue con *@dest* a toda velocidad',
'corrió tan rápido con *@dest* que desaparecieron',
'arrancó a correr con *@dest* sin mirar atrás',
 ],
 solo: [
'salió corriendo del chat sin decir nada',
'escapó a toda velocidad sin motivo',
'se fue corriendo y no dijo a dónde',
'salió disparado/a como si lo/la persiguieran',
'huyó del chat a toda prisa',
 ],
 },
 run: {
 emoji:'', nekos:'run',
 mencion: [
'corrió con *@dest* sin parar',
'se puso a correr junto a *@dest*',
'salió disparado/a con *@dest* a toda velocidad',
'no pudo seguir el ritmo de *@dest* corriendo',
'escapó junto a *@dest* como si fuera la última vez',
 ],
 solo: [
'salió corriendo del chat a toda pastilla',
'se fue corriendo sin despedirse de nadie',
'está corriendo por el chat y no se sabe por qué',
'huyó del grupo a toda velocidad',
'arrancó a correr y no piensa volver pronto',
 ],
 },
 triste: {
 emoji:'', nekos:'sad',
 mencion: [
'está muy triste por *@dest*',
'llora en silencio pensando en *@dest*',
'se puso deprimido/a por culpa de *@dest*',
'anda con el ánimo por los suelos por *@dest*',
'no puede dejar de pensar triste en *@dest*',
 ],
 solo: [
'está triste y no quiere hablar con nadie',
'anda con el ánimo por los suelos hoy',
'se siente solo/a y muy triste',
'está de bajón total en el chat',
'tristeza modo activado, alguien que lo/la anime',
 ],
 },
 sad: {
 emoji:'', nekos:'sad',
 mencion: [
'está sad por culpa de *@dest*',
'se pone muy triste mirando a *@dest*',
'derrama una lagrimita pensando en *@dest*',
'anda deprimido/a por *@dest*',
'siente un vacío enorme desde que *@dest* hizo eso',
 ],
 solo: [
'está sad y no sabe bien por qué',
'el mood de hoy es: tristeza profunda',
'anda con cara de perrito abandonado/a',
'necesita que alguien lo/la anime',
'está en modo sad y no hay quien lo/la saque',
 ],
 },
 enojado: {
 emoji:'', nekos:'baka',
 mencion: [
'está muy enojado/a con *@dest*',
'le gritó BAKA a *@dest* sin contemplaciones',
'está furioso/a con *@dest* y no lo/la perdona',
'le puso mala cara a *@dest*',
'tiene muchas ganas de regañar a *@dest*',
 ],
 solo: [
'está enojado/a sin motivo aparente',
'anda furioso/a con el mundo entero',
'tiene cara de pocos amigos hoy',
'está de mal humor y es mejor no acercarse',
'modo enojado activado, nadie le hable',
 ],
 },
 angry: {
 emoji:'', nekos:'baka',
 mencion: [
'está muy angry con *@dest*',
'le mandó un BAKA épico a *@dest*',
'está a punto de explotar de rabia con *@dest*',
'fulminó a *@dest* con la mirada',
'regañó a *@dest* sin dejar que respondiera',
 ],
 solo: [
'está angry y no quiere hablar con nadie',
'anda furioso/a por el chat, mejor apartarse',
'tiene el modo angry activado al 100%',
'está echando fuego por las orejas',
'angry mode ON, nadie se le acerque',
 ],
 },
 saludar: {
 emoji:'', nekos:'wave',
 mencion: [
'saludó a *@dest* agitando la mano con entusiasmo',
'le hizo señas a *@dest* desde lejos',
'mandó un gran saludo a *@dest*',
'no paró de agitar la mano hacia *@dest*',
'le gritó el saludo más efusivo a *@dest*',
 ],
 solo: [
'saludó a todo el grupo con entusiasmo',
'manda un saludo gigante a todo el chat',
'agita la mano para que todos lo/la vean',
'dice hola a quien quiera responder',
'¡Hola a todos! — gritó alegremente al chat',
 ],
 },
 wave: {
 emoji:'', nekos:'wave',
 mencion: [
'le hizo un wave enorme a *@dest*',
'saludó a *@dest* agitando el brazo desde lejos',
'mandó un saludo cómplice a *@dest*',
'no dejó de saludar a *@dest* hasta que respondió',
'le hizo señas imposibles de ignorar a *@dest*',
 ],
 solo: [
'hace wave al chat entero',
'saluda al vacío porque nadie le presta atención',
'agita la mano con mucho entusiasmo',
'manda un wave a quien quiera recibirlo',
'saluda a todo el mundo aunque nadie responda',
 ],
 },
 greet: {
 emoji:'', nekos:'wave',
 mencion: [
'saludó formalmente a *@dest* con una reverencia',
'le dio la bienvenida a *@dest* al chat',
'saludó a *@dest* con una gran sonrisa',
'no dejó de saludar a *@dest* en todo el rato',
'recibió a *@dest* con los brazos abiertos',
 ],
 solo: [
'saludó al grupo con mucha educación',
'da los buenos días/tardes/noches al chat',
'saluda a todos los presentes del grupo',
'llegó al chat y saludó a todos',
'¡Buenas a tod@s! — anunció al entrar al grupo',
 ],
 },
 hi: {
 emoji:'', nekos:'wave',
 mencion: [
'¡HI! le gritó a *@dest* en pleno chat',
'saludó a *@dest* con un hi muy animado',
'entró al chat solo para saludar a *@dest*',
'mandó un hola enorme a *@dest*',
'no pudo resistirse a saludar a *@dest*',
 ],
 solo: [
'¡Hi! — saludó al chat sin más',
'entró solo para decir hi a todo el mundo',
'manda un hi gigante a quien lo lea',
'saluda al chat con toda la energía del mundo',
'hi hi hi a todo el grupo sin excepción',
 ],
 },
 aburrido: {
 emoji:'', nekos:'bored',
 mencion: [
'se aburre muchísimo con *@dest*',
'bostezó en la cara de *@dest* sin vergüenza',
'se quedó dormido/a escuchando a *@dest*',
'definitivamente se muere de aburrimiento con *@dest*',
'no puede aguantar más el aburrimiento de *@dest*',
 ],
 solo: [
'está aburrido/a y no sabe qué hacer con su vida',
'bosteza sin parar en el chat',
'anda sin tener qué hacer y se muere del aburrimiento',
'se muere de tedio en el chat',
'el aburrimiento lo/la tiene en modo zombie',
 ],
 },
 bored: {
 emoji:'', nekos:'bored',
 mencion: [
'está súper bored gracias a *@dest*',
'se quedó dormido/a de aburrimiento con *@dest*',
'bostezó monumentalmente en la cara de *@dest*',
'perdió el hilo de la conversación de *@dest* hace rato',
'ni *@dest* lo/la salva de este aburrimiento',
 ],
 solo: [
'modo bored activado al máximo',
'está tan aburrido/a que habla solo/a',
'el aburrimiento es tan grande que se podría tocar',
'está contando las baldosas del chat de puro aburrimiento',
'nada ni nadie lo/la divierte en el chat',
 ],
 },
 bofetada: {
 emoji:'', nekos:'facepalm',
 mencion: [
'se hizo un facepalm épico por culpa de *@dest*',
'no puede creer lo que acaba de hacer *@dest*',
'se cubre la cara de vergüenza ajena por *@dest*',
'perdió toda la fe en la humanidad por culpa de *@dest*',
'se puso la mano en la frente mirando a *@dest*',
 ],
 solo: [
'se hace un facepalm monumental',
'no puede creer lo que está leyendo en el chat',
'la vergüenza ajena le golpea con fuerza',
'se cubre la cara sin poder creer lo que ve',
'facepalm máximo, esto ya es demasiado',
 ],
 },
 facepalm: {
 emoji:'', nekos:'facepalm',
 mencion: [
'facepalm total por lo que hizo *@dest*',
'se pone la mano en la cara al ver a *@dest*',
'no tiene palabras para lo que acaba de hacer *@dest*',
'le sobrevino un facepalm por cada cosa que dice *@dest*',
'ay *@dest*... facepalm',
 ],
 solo: [
'facepalm de proporciones épicas',
'se golpea la frente sin poder evitarlo',
'esto merece un facepalm de campeonato',
'el chat lo/la tiene en modo facepalm constante',
'facepalm infinito para lo que está viendo',
 ],
 },
 feliz: {
 emoji:'', nekos:'happy',
 mencion: [
'está súper feliz con *@dest*',
'no puede dejar de sonreír al lado de *@dest*',
'la alegría le explota por dentro al ver a *@dest*',
'está irradiando felicidad gracias a *@dest*',
'se alegra muchísimo de estar con *@dest*',
 ],
 solo: [
'está de muy buen humor hoy sin razón aparente',
'anda feliz por el chat contagiando energía',
'irradia buena vibra por todos lados',
'tiene una sonrisa que no se le borra',
'la felicidad le sale por los poros hoy',
 ],
 },
 happy: {
 emoji:'', nekos:'happy',
 mencion: [
'está muy happy al lado de *@dest*',
'se alegra un montón de ver a *@dest*',
'sonríe de oreja a oreja por *@dest*',
'la felicidad lo/la invade gracias a *@dest*',
'está en modo happy total por *@dest*',
 ],
 solo: [
'está happy y quiere que todos lo sepan',
'anda con la sonrisa pegada en la cara',
'la buena vibra de hoy no tiene explicación',
'está en modo happy activado 100%',
'felicidad pura en el chat hoy',
 ],
 },
 pensar: {
 emoji:'', nekos:'think',
 mencion: [
'está pensando profundamente en *@dest*',
'no puede dejar de darle vueltas al tema de *@dest*',
'reflexiona sobre *@dest* con mucha seriedad',
'caviló durante horas en lo de *@dest*',
'tiene la mente ocupada 100% con *@dest*',
 ],
 solo: [
'está pensando en el chat con cara de filósofo/a',
'perdido/a en sus propios pensamientos',
'anda cavilando algo muy profundo',
'la mente le va a mil por hora',
'piensa tanto que le va a salir humo de la cabeza',
 ],
 },
 think: {
 emoji:'', nekos:'think',
 mencion: [
'está pensando muy seriamente en *@dest*',
'no puede sacar a *@dest* de su cabeza',
'reflexiona sobre lo que dijo *@dest*',
'le da mil vueltas al asunto de *@dest*',
'tiene a *@dest* muy presente en sus pensamientos',
 ],
 solo: [
'está en modo think profundo',
'piensa demasiado para su propio bien',
'lost in thoughts en medio del chat',
'anda con la cabeza en las nubes pensando',
'tiene mil pensamientos y no sabe por cuál empezar',
 ],
 },
 dormir: {
 emoji:'', nekos:'sleep',
 mencion: [
'se quedó dormido/a en el hombro de *@dest*',
'usó a *@dest* de almohada y cayó ko',
'se durmió encima de *@dest* sin pedir permiso',
'cayó rendido/a al lado de *@dest* roncando',
'se acomodó contra *@dest* y empezó a roncar',
 ],
 solo: [
'se quedó dormido/a en pleno chat',
'se durmió sin avisar a nadie',
'está roncando en el chat ahora mismo',
'cayó rendido/a y ni las notificaciones lo/la despiertan',
'está en el país de los sueños, no molestar',
 ],
 },
 sleep: {
 emoji:'', nekos:'sleep',
 mencion: [
'se durmió encima de *@dest* sin avisar',
'usó el hombro de *@dest* de almohada y no hay quien lo/la despierte',
'se quedó dormido/a agarrado/a a *@dest*',
'ronca tranquilamente sobre *@dest*',
'cayó en los brazos de *@dest* rendido/a de sueño',
 ],
 solo: [
'zzzZZZ... se quedó dormido/a',
'entró al modo sleep y no hay vuelta atrás',
'está soñando en pleno chat',
'se fue a la tierra de los sueños sin despedirse',
'duerme profundamente y ronca tranquilamente',
 ],
 },
 guinar: {
 emoji:'', nekos:'wink',
 mencion: [
'le guiñó el ojo a *@dest* con mucha picardía',
'le mandó un guiño cómplice a *@dest*',
'le hizo un ojito cargado de intención a *@dest*',
'guiñó el ojo mirando fijamente a *@dest*',
'le tiró un guiño misterioso a *@dest*',
 ],
 solo: [
'guiñó el ojo al chat con mucha picardía',
'manda un guiño misterioso sin decir a quién',
'anda guiñando el ojo sin motivo aparente',
'les lanzó un guiño a todos los del grupo',
'el guiño más misterioso del chat fue suyo',
 ],
 },
 wink: {
 emoji:'', nekos:'wink',
 mencion: [
'winkeó a *@dest* con mucho descaro',
'le tiró el guiño más pícaro del universo a *@dest*',
'le hizo ojitos irresistibles a *@dest*',
'guiñó el ojo a *@dest* con toda la intención del mundo',
'le mandó el wink más cargado de significado a *@dest*',
 ],
 solo: [
'wink al chat entero',
'anda guiñando el ojo a quien quiera interpretarlo',
'el guiño más pícaro del chat es suyo',
'wink misterioso al aire',
'guiñó el ojo y nadie sabe qué quiso decir',
 ],
 },
 lamer: {
 emoji:'', nekos:'lick',
 mencion: [
'lamió a *@dest* de arriba abajo sin avisar',
'le pasó la lengua por la mejilla a *@dest*',
'lamió la cara de *@dest* como si fuera un helado',
'le pegó un lametón enorme a *@dest*',
'usó a *@dest* de paleta y no paró de lamer',
 ],
 solo: [
'lamió el aire porque no hay nadie a quien lamer',
'anda lamiendo lo que encuentra a su paso',
'tiene la lengua fuera buscando a quién lamer',
'lamió el teclado de puro aburrimiento',
'modo lametón activado y sin víctima disponible',
 ],
 },
 lick: {
 emoji:'', nekos:'lick',
 mencion: [
'lickeó a *@dest* sin el menor pudor',
'le dio el lametón más enorme del chat a *@dest*',
'se acercó sigilosamente a *@dest* y le lamió la mejilla',
'trató a *@dest* como si fuera un lollipop',
'le pasó la lengua por el cuello a *@dest*',
 ],
 solo: [
'lick al aire porque sí',
'anda en modo gecko lamiendo todo lo que toca',
'tiene la lengua fuera esperando a alguien',
'lickeó el suelo digital del chat',
'lame el aire buscando a su víctima favorita',
 ],
 },
 cosquillas: {
 emoji:'', nekos:'tickle',
 mencion: [
'le hizo cosquillas a *@dest* sin ninguna compasión',
'atacó a *@dest* con cosquillas por todos lados',
'encontró el punto débil de *@dest* y atacó sin piedad',
'no paró de hacerle cosquillas a *@dest* hasta que se rindió',
'torturó a *@dest* con cosquillas interminables',
 ],
 solo: [
'hace cosquillas en el aire por falta de víctima',
'anda buscando a quién hacerle cosquillas',
'tiene los dedos listos para atacar a quien se acerque',
'quiere hacer cosquillas a alguien del grupo',
'practica sus técnicas de cosquillas en el vacío',
 ],
 },
 tickle: {
 emoji:'', nekos:'tickle',
 mencion: [
'tickleó a *@dest* sin misericordia',
'encontró los puntos de cosquillas secretos de *@dest*',
'hizo a *@dest* llorar de risa con sus cosquillas',
'atacó a *@dest* por los costados con los dedos',
'no hay defensa posible contra los tickles de *@dest*',
 ],
 solo: [
'busca a quién ticklear urgentemente',
'tiene los dedos en posición de ataque y nadie enfrente',
'quiere hacer cosquillas a alguien del chat',
'anda en modo tickle attack sin víctima',
'practica sus mejores técnicas de cosquillas en el aire',
 ],
 },
 comer: {
 emoji:'', nekos:'nom',
 mencion: [
'comió junto a *@dest* sin parar',
'compartió su comida favorita con *@dest*',
'invitó a *@dest* a comer y no dejó ni las migas',
'devoró todo junto a *@dest* en tiempo récord',
'no paró de comer al lado de *@dest*',
 ],
 solo: [
'comió solo/a y sin remordimientos',
'se puso a comer en pleno chat sin ofrecer nada',
'devoró todo lo que encontró',
'comió como si no hubiera mañana',
'nom nom nom solo/a en el chat',
 ],
 },
 eat: {
 emoji:'', nekos:'nom',
 mencion: [
'comió con *@dest* y no dejaron nada',
'le ofreció comida a *@dest* y compartieron todo',
'se pegó un festín junto a *@dest*',
'invitó a *@dest* a comer y disfrutaron mucho',
'nom nom nom con *@dest* sin parar',
 ],
 solo: [
'está comiendo solo/a en el chat',
'nom nom nom sin compartir con nadie',
'se puso a comer sin avisar a nadie',
'devoró su comida favorita en solitario',
'come en el chat y no invita a nadie',
 ],
 },
 matar: {
 emoji:'', nekos:'kill',
 mencion: [
'eliminó a *@dest* del chat',
'le declaró la guerra a *@dest* y no falló',
'vino directo por *@dest* y terminó el trabajo',
'ejecutó a *@dest* sin contemplaciones',
'borró a *@dest* del mapa sin pestañear',
 ],
 solo: [
'busca a quién eliminar del chat',
'anda de caza por el grupo',
'está listo/a para la batalla y busca rival',
'busca su próxima víctima con determinación',
'modo asesino activado, nadie está a salvo',
 ],
 },
 kill: {
 emoji:'', nekos:'kill',
 mencion: [
'killeó a *@dest* sin dudarlo un segundo',
'eliminó a *@dest* del mapa permanentemente',
'se encargó de *@dest* sin hacer ruido',
'acabó con *@dest* de un solo movimiento',
'ejecutó a *@dest* con precisión quirúrgica',
 ],
 solo: [
'modo kill activado y sin objetivo fijo',
'anda buscando a quién eliminar del grupo',
'tiene el arma lista y nadie a quien apuntar',
'la violencia lo/la llama y no tiene víctima',
'está en modo hunter buscando presa por el chat',
 ],
 },
 seducir: {
 emoji:'', nekos:'seduce',
 mencion: [
'sedujo a *@dest* con su mirada más pícara',
'intentó seducir a *@dest* y lo/la dejó sin palabras',
'le lanzó una mirada cargada de intención a *@dest*',
'puso su mejor cara de seductor/a ante *@dest*',
'irresistiblemente sedujo a *@dest*',
 ],
 solo: [
'está siendo irresistiblemente seductor/a',
'anda seduciendo al grupo entero sin querer',
'tiene una sonrisa que lo dice todo',
'irradia vibras misteriosas y seductoras',
'modo seducción activado aunque no haya nadie',
 ],
 },
 seduce: {
 emoji:'', nekos:'seduce',
 mencion: [
'seduceó a *@dest* con descaro total',
'no paró de lanzarle miradas a *@dest*',
'le puso los ojos encima a *@dest* con mucha intención',
'sonrió misteriosamente mirando a *@dest*',
'hipnotizó a *@dest* con su carisma irresistible',
 ],
 solo: [
'seduce al chat entero sin esfuerzo',
'está en modo seductor/a sin nadie que lo/la frene',
'lanza vibras de seducción al vacío',
'irradia encanto por todos los poros',
'modo rizz: activado aunque no haya destinatario',
 ],
 },
 patear: {
 emoji:'', nekos:'kick',
 mencion: [
'pateó a *@dest* con todas sus fuerzas',
'le dio una patada voladora a *@dest*',
'le pateó el trasero a *@dest* sin miramientos',
'mandó a volar a *@dest* de una patada',
'le estampó el pie en la cara a *@dest*',
 ],
 solo: [
'pateó al aire con mucha rabia',
'anda buscando a quién patear',
'practica sus patadas en el viento',
'tiene el pie listo para quien se le acerque',
'patada al vacío porque no hay nadie a quién darle',
 ],
 },
 kick: {
 emoji:'', nekos:'kick',
 mencion: [
'kickeó a *@dest* sin compasión',
'le metió una patada épica a *@dest*',
'mandó a *@dest* por los aires de una patada',
'le dio el kick más potente del chat a *@dest*',
'no dudó un segundo en patear a *@dest*',
 ],
 solo: [
'kick al aire por falta de objetivo',
'anda repartiendo patadas al viento',
'practica sus kicks en el chat vacío',
'tiene el pie caliente y nadie a quien patear',
'modo kickboxing activado y sin rival enfrente',
 ],
 },
 tomar: {
 emoji:'', nekos:'handhold',
 mencion: [
'tomó de la mano a *@dest* suavemente',
'entrelazó sus dedos con los de *@dest*',
'no soltó la mano de *@dest* en ningún momento',
'le ofreció su mano a *@dest* tímidamente',
'agarró la mano de *@dest* y no la soltó',
 ],
 solo: [
'busca de quién agarrarse en el chat',
'tiene la mano extendida esperando a alguien',
'anda buscando una mano cálida que tomar',
'quiere tomarse de la mano con alguien del grupo',
'mano extendida, ¿alguien se apunta?',
 ],
 },
 handhold: {
 emoji:'', nekos:'handhold',
 mencion: [
'tomó de la mano a *@dest* y no la suelta',
'entrelazó sus dedos con los de *@dest* sin avisar',
'agarró la mano de *@dest* tímidamente',
'holdea la mano de *@dest* con mucho cariño',
'se puso rojo/a de coger la mano de *@dest*',
 ],
 solo: [
'busca una mano que agarrar en el grupo',
'mano extendida hacia el chat esperando a alguien',
'quiere handhold con alguien desesperadamente',
'tiene la mano lista para quien quiera tomarla',
'holdea el aire esperando que alguien llegue',
 ],
 },
 bath: {
 emoji:'', nekos:'bath',
 mencion: [
'se metió en el baño con *@dest* sin avisar',
'invitó a *@dest* a bañarse juntos/as',
'salpicó a *@dest* con agua de la bañera',
'compartió la bañera con *@dest* tranquilamente',
'se está bañando con *@dest* y nadie entiende nada',
 ],
 solo: [
'se metió en la bañera solo/a sin invitar a nadie',
'está disfrutando el baño en solitario',
'splish splash en el baño solo/a',
'se está dando un baño relajante y no quiere compañía',
'baño solitario en el chat, nadie moleste',
 ],
 },
 bleh: {
 emoji:'', nekos:'bleh',
 mencion: [
'le sacó la lengua a *@dest* con mucho descaro',
'hizo una mueca burlona a *@dest*',
'se burló de *@dest* sacando la lengua',
'le hizo bleh a *@dest* sin ningún pudor',
'le hizo la pedorreta a *@dest*',
 ],
 solo: [
'saca la lengua al chat entero',
'bleh para todos en general',
'hace muecas al aire sin razón',
'se burla de la nada en el chat',
'bleh bleh bleh sin destinatario concreto',
 ],
 },
 call: {
 emoji:'', nekos:'wave',
 mencion: [
'llamó a *@dest* y no para de timbrar',
'está intentando comunicarse con *@dest*',
'le marcó el teléfono a *@dest* sin parar',
'llama a *@dest* desde el chat a ver si responde',
'alo alo, ¿está *@dest*?',
 ],
 solo: [
'llama a alguien del grupo pero nadie contesta',
'está timbran a todo el chat sin suerte',
'alo alo... ¿hay alguien ahí?',
'marca números al azar en el grupo',
'espera que alguien le conteste la llamada',
 ],
 },
 clap: {
 emoji:'', nekos:'highfive',
 mencion: [
'aplaudió a *@dest* con mucho entusiasmo',
'le dio una ovación de pie a *@dest*',
'no paró de aplaudir por lo que hizo *@dest*',
'le regaló los mejores aplausos del chat a *@dest*',
'standing ovation para *@dest*',
 ],
 solo: [
'aplaudió solo/a en el chat porque nadie más lo hizo',
'aplaude sin importarle que nadie le siga',
'clap clap clap al vacío',
'se aplaudió a sí mismo/a con orgullo',
'aplaude al chat entero por existir',
 ],
 },
 aplaudir: {
 emoji:'', nekos:'highfive',
 mencion: [
'aplaudió a *@dest* sin parar',
'le dio una ovación merecida a *@dest*',
'no pudo evitar aplaudir lo que hizo *@dest*',
'se puso de pie para aplaudir a *@dest*',
'bravo bravo a *@dest*',
 ],
 solo: [
'aplaude al chat aunque nadie lo/la vea',
'clap clap clap solo/a sin razón',
'se aplaude a sí mismo/a porque se lo merece',
'aplaude a todo el grupo por igual',
'ovación solitaria en el chat',
 ],
 },
 coffee: {
 emoji:'', nekos:'coffee',
 mencion: [
'tomó café con *@dest* y no dijo nada en todo el rato',
'invitó a *@dest* a un café y conversaron largo',
'compartió su taza de café favorita con *@dest*',
'tomó el café de la mañana junto a *@dest*',
'café para dos: *@dest* y yo',
 ],
 solo: [
'tomó café solo/a y en silencio',
'se hizo un café y no invitó a nadie',
'café matutino en solitario sin remordimientos',
'sorbió su café favorito solo/a en el chat',
'una taza de café y nada más, gracias',
 ],
 },
 cafe: {
 emoji:'', nekos:'coffee',
 mencion: [
'se tomó un café con *@dest* tranquilamente',
'invitó a *@dest* a un cafecito',
'compartió el café de la tarde con *@dest*',
'sorber café con *@dest* es su actividad favorita',
'cafecito para *@dest* y para mí',
 ],
 solo: [
'se tomó su café solo/a y disfrutándolo',
'cafe solito porque nadie le hizo compañía',
'sorbe su café favorito en solitario',
'nadie merece su café hoy',
'cafecito tranquilo sin compañía',
 ],
 },
 cold: {
 emoji:'', nekos:'cold',
 mencion: [
'tiene mucho frío y se pegó a *@dest* buscando calor',
'está helado/a y culpa a *@dest* por alguna razón',
'tiembla de frío al lado de *@dest*',
'busca el calor de *@dest* porque se está congelando',
'brrrr... se pegó a *@dest* como si fuera una estufa',
 ],
 solo: [
'tiene un frío terrible y nadie le da calor',
'se está congelando en el chat',
'brrrr, alguien que le traiga una manta',
'el frío lo/la tiene temblando en el grupo',
'se murió de frío antes de que nadie llegara',
 ],
 },
 cook: {
 emoji:'', nekos:'cook',
 mencion: [
'cocinó algo delicioso para *@dest*',
'se puso a cocinar especialmente para *@dest*',
'hizo su mejor plato y se lo ofreció a *@dest*',
'cocinó con todo el amor del mundo para *@dest*',
'el menú de hoy es especial para *@dest*',
 ],
 solo: [
'cocinó algo increíble y no invitó a nadie',
'se puso a cocinar solo/a y olió de maravilla',
'chef mode activado en solitario',
'cocinó para sí mismo/a porque nadie lo merece',
'se hizo el mejor plato del mundo y no compartió',
 ],
 },
 dramatic: {
 emoji:'', nekos:'dramatic',
 mencion: [
'está siendo extremadamente dramático/a con *@dest*',
'actuó la escena más dramática del chat con *@dest*',
'convirtió cualquier cosa de *@dest* en un drama épico',
'no puede dejar de dramatizar todo lo que hace *@dest*',
'Oscar a la actuación más dramática por culpa de *@dest*',
 ],
 solo: [
'está en modo drama total sin motivo',
'convirtió el chat en un teatro de su drama',
'el drama lo/la persigue aunque esté solo/a',
'actuación dramática de máximo nivel sin audiencia',
'gana el Oscar al drama más innecesario del día',
 ],
 },
 drama: {
 emoji:'', nekos:'dramatic',
 mencion: [
'montó un drama épico alrededor de *@dest*',
'hizo de cualquier gesto de *@dest* toda una telenovela',
'dramatizó sin parar con *@dest* como protagonista',
'sin *@dest* no habría drama, pero aquí estamos',
'le montó el drama más grande del chat a *@dest*',
 ],
 solo: [
'el drama empieza y termina con él/ella',
'monodrama en el chat de la más alta calidad',
'drama de una persona, aplausos de cero',
'convirtió el chat en su escenario personal',
'drama puro sin necesidad de coprotagonista',
 ],
 },
 draw: {
 emoji:'', nekos:'draw',
 mencion: [
'dibujó algo increíble para *@dest*',
'le hizo un retrato a *@dest* con mucho detalle',
'se pasó horas dibujando algo para *@dest*',
'le dedicó su mejor dibujo a *@dest*',
'arte exclusivo hecho con amor para *@dest*',
 ],
 solo: [
'dibujó algo y no lo quiso mostrar a nadie',
'se puso a dibujar en solitario y quedó genial',
'arte modo solo activado',
'dibujó su obra maestra sin que nadie la vea',
'se puso creativo/a y nadie lo supo',
 ],
 },
 drunk: {
 emoji:'', nekos:'drunk',
 mencion: [
'está borracho/a y se colgó del cuello de *@dest*',
'bebió de más y le habla solo a *@dest*',
'está en modo drunk y *@dest* tiene que aguantarlo/la',
'le contó todos sus secretos a *@dest* después de unas copas',
'borracho/a perdido/a junto a *@dest*',
 ],
 solo: [
'está borracho/a y eso explica todo',
'pedo perdido/a en el chat',
'las copas lo/la tienen en modo incoherente',
'está celebrando solo/a y ya se le fue la mano',
'drunk mode activado, mejor no hacerle caso',
 ],
 },
 gaming: {
 emoji:'', nekos:'gaming',
 mencion: [
'está jugando videojuegos con *@dest* y no para',
'invitó a *@dest* a una partida y llevan horas',
'no quiere dejar de jugar con *@dest*',
'se puso a jugar con *@dest* y olvidaron la hora',
'la alianza gaming con *@dest* es imparable',
 ],
 solo: [
'está jugando videojuegos solo/a y no quiere que lo/la molesten',
'modo gaming activado, no disponible para el chat',
'solo mode gaming en marcha',
'está en plena partida y nadie puede distraerlo/la',
'gamer solitario/a que no quiere ser molestado/a',
 ],
 },
 heat: {
 emoji:'', nekos:'heat',
 mencion: [
'tiene un calor terrible y le echó la culpa a *@dest*',
'está derritiéndose de calor al lado de *@dest*',
'busca sombra junto a *@dest* porque se funde',
'el calor lo/la tiene sin fuerzas al lado de *@dest*',
'sudando sin parar con *@dest* cerca',
 ],
 solo: [
'tiene un calor insoportable y necesita un ventilador',
'se está derritiendo en el chat',
'el calor lo/la tiene en modo zombie',
'alguien que le traiga un helado por favor',
'se funde de calor y nadie hace nada',
 ],
 },
 jump: {
 emoji:'', nekos:'yeet',
 mencion: [
'saltó encima de *@dest* sin avisar',
'se lanzó hacia *@dest* con un salto épico',
'saltó de alegría junto a *@dest*',
'pegó un salto tremendo al ver a *@dest*',
'se impulsó hacia *@dest* con un salto de campeón/a',
 ],
 solo: [
'saltó al vacío del chat sin mirar',
'pegó un brinco enorme sin motivo aparente',
'saltó sin red y sin destinatario',
'se tiró al vacío digital con mucho estilo',
'salto épico en solitario, nadie lo vio',
 ],
 },
 lewd: {
 emoji:'', nekos:'smug',
 mencion: [
'está siendo muy lascivo/a con *@dest*',
'le lanzó la mirada más lewd del chat a *@dest*',
'le coqueteó sin vergüenza alguna a *@dest*',
'convirtió cualquier cosa de *@dest* en algo lewd',
'modo lewd activado 100% apuntando a *@dest*',
 ],
 solo: [
'está en modo lewd y no hay quién lo/la pare',
'mente sucia sin destinatario concreto',
'lewd mode activado aunque no haya nadie',
'sus pensamientos son un desastre hoy',
'modo lascivo/a: ON, audiencia: nadie',
 ],
 },
 love: {
 emoji:'', nekos:'hug',
 mencion: [
'está profundamente enamorado/a de *@dest*',
'no puede dejar de pensar en *@dest* ni un segundo',
'el amor que siente por *@dest* no tiene límites',
'se le salen los corazones de los ojos al ver a *@dest*',
'está loco/a de amor por *@dest*',
 ],
 solo: [
'está enamorado/a y no dice de quién',
'el amor le sale por todos los poros hoy',
'corazones flotando alrededor de su cabeza',
'está en modo enamorado/a sin remedio',
'el amor lo/la tiene en las nubes sin aterrizar',
 ],
 },
 amor: {
 emoji:'', nekos:'hug',
 mencion: [
'está lleno/a de amor por *@dest*',
'quiere a *@dest* con toda su alma',
'el amor que siente por *@dest* es incondicional',
'no hay nadie en el chat que quiera más que a *@dest*',
'corazón rebosante de amor hacia *@dest*',
 ],
 solo: [
'tiene tanto amor que no sabe dónde ponerlo',
'el amor le desborda en el chat',
'anda repartiendo amor gratis para quien lo quiera',
'lleno/a de amor hoy sin saber bien para quién',
'el amor lo/la tiene flotando en el chat',
 ],
 },
 nope: {
 emoji:'', nekos:'shrug',
 mencion: [
'le dijo que no a *@dest* con mucha determinación',
'rechazó todo lo que propuso *@dest*',
'nope nope nope a *@dest* sin contemplaciones',
'se negó rotundamente ante *@dest*',
'la respuesta para *@dest* siempre es no',
 ],
 solo: [
'nope a todo en el chat',
'se negó sin dar explicaciones',
'su respuesta es no y punto',
'nope nope nope al chat entero',
'rechazo masivo a todo lo que venga',
 ],
 },
 pout: {
 emoji:'', nekos:'baka',
 mencion: [
'está haciendo pucheros por culpa de *@dest*',
'no puede creer lo que hizo *@dest* y hace pucheros',
'pucheros infinitos dirigidos a *@dest*',
'está enfurruñado/a con *@dest* y lo demuestra',
'puchero monumental por lo que hizo *@dest*',
 ],
 solo: [
'hace pucheros en el chat sin motivo aparente',
'está enfurruñado/a con el mundo entero',
'puchero mode: activado',
'está de morros y nadie sabe por qué',
'pucheros al vacío porque le apetece',
 ],
 },
 psycho: {
 emoji:'', nekos:'psycho',
 mencion: [
'se puso en modo psicópata con *@dest*',
'la mirada que le lanzó a *@dest* no era normal',
'planificó algo retorcido contra *@dest*',
'le sonrió a *@dest* de una forma muy inquietante',
'psycho mode activado y *@dest* es el objetivo',
 ],
 solo: [
'entró en modo psicópata sin destinatario',
'está planeando algo y nadie sabe qué',
'la mirada dice demasiado hoy',
'psycho mode: ON, víctima: pendiente',
'ríe en silencio y eso da más miedo que cualquier otra cosa',
 ],
 },
 push: {
 emoji:'', nekos:'kick',
 mencion: [
'empujó a *@dest* sin ningún motivo',
'le dio un empujón a *@dest* de la nada',
'mandó a *@dest* de un lado a otro de un empujón',
'empujó a *@dest* con toda su fuerza',
'bum, *@dest* cayó de un empujón',
 ],
 solo: [
'empujó el aire porque no hay nadie a quien empujar',
'anda dando empujones al viento',
'tiene ganas de empujar a alguien del grupo',
'empuja sin víctima y eso lo frustra',
'modo empujón activado y sin objetivo',
 ],
 },
 scared: {
 emoji:'', nekos:'scared',
 mencion: [
'se asustó muchísimo por culpa de *@dest*',
'pegó un grito de terror al ver lo que hizo *@dest*',
'tiene miedo de *@dest* y no lo oculta',
'se escondió detrás del chat por culpa de *@dest*',
'el susto que le dio *@dest* no lo/la supera',
 ],
 solo: [
'está asustado/a y no sabe de qué',
'pegó un grito al chat sin razón aparente',
'tiene miedo de algo y no quiere decir qué',
'se esconde en un rincón del chat',
'modo asustado/a activado sin motivo claro',
 ],
 },
 scream: {
 emoji:'', nekos:'scream',
 mencion: [
'le gritó a *@dest* con todas sus fuerzas',
'le metió el grito más épico del chat a *@dest*',
'no pudo evitar gritar al ver lo que hizo *@dest*',
'AAAAAAA le gritó directamente a *@dest*',
'perdió los papeles y gritó a *@dest* sin parar',
 ],
 solo: [
'gritó al vacío del chat',
'AAAAAAA sin destinatario concreto',
'el grito interior salió al exterior',
'gritó porque le apetecía y punto',
'grito al chat entero sin explicación',
 ],
 },
 shy: {
 emoji:'', nekos:'blush',
 mencion: [
'está muy tímido/a con *@dest*',
'no puede mirar a *@dest* de lo tímido/a que es',
'se esconde al ver a *@dest*',
'le hablaría a *@dest* pero la timidez no lo/la deja',
'se pone rojo/a solo de pensar en *@dest*',
 ],
 solo: [
'está tímido/a en el chat hoy',
'se esconde detrás de la pantalla',
'la timidez lo/la tiene en silencio',
'quiere hablar pero la vergüenza lo/la frena',
'modo shy activado: cero interacciones',
 ],
 },
 timido: {
 emoji:'', nekos:'blush',
 mencion: [
'se puso muy tímido/a con *@dest*',
'no hay manera de que mire a *@dest* a los ojos',
'se sonrojó y escondió la cara al ver a *@dest*',
'la timidez lo/la domina cuando está con *@dest*',
'quiere acercarse a *@dest* pero no puede',
 ],
 solo: [
'está tan tímido/a que apenas escribe',
'la vergüenza lo/la tiene en modo invisible',
'modo tímido/a: activado',
'quiere participar en el chat pero no se atreve',
'timidez máxima hoy y sin cura aparente',
 ],
 },
 sing: {
 emoji:'', nekos:'sing',
 mencion: [
'cantó su canción favorita para *@dest*',
'le dedicó una canción entera a *@dest*',
'se arrancó a cantar mirando a *@dest*',
'usó a *@dest* de audiencia para su concierto privado',
'la voz más hermosa del chat sonó para *@dest*',
 ],
 solo: [
'cantó solo/a en el chat y fue increíble',
'concierto privado sin público en el grupo',
'se arrancó a cantar sin pedir permiso',
'la canción salió sola y sonó fenomenal',
'karaoke solitario en el chat, nadie aplaudió',
 ],
 },
 smoke: {
 emoji:'', nekos:'smoke',
 mencion: [
'está fumando tranquilamente con *@dest*',
'compartió un cigarro con *@dest* en silencio',
'fuma al lado de *@dest* sin decir nada',
'le ofreció fuego a *@dest* con mucho estilo',
'momento cigarro con *@dest* en el chat',
 ],
 solo: [
'fuma solo/a en el chat con cara de interesante',
'cigarro solitario y cara de pocos amigos',
'fumando en el rincón del chat sin compañía',
'humo en el chat, sin comentarios',
'modo fumador/a misteriosos/a: activado',
 ],
 },
 spit: {
 emoji:'', nekos:'baka',
 mencion: [
'le escupió a *@dest* de la manera más asquerosa',
'ptui, escupió justo en dirección a *@dest*',
'le lanzó un escupitajo a *@dest* sin avergonzarse',
'decidió que *@dest* merecía un escupitajo',
'le escupió con mucha puntería a *@dest*',
 ],
 solo: [
'escupió al aire porque tiene el poder',
'escupitajo al vacío sin destinatario',
'ptui al chat en general',
'lanzó un escupitajo enorme sin apuntar',
'escupitajo máster en el chat',
 ],
 },
 escupir: {
 emoji:'', nekos:'baka',
 mencion: [
'escupió en la dirección de *@dest* sin pensarlo',
'le lanzó un escupitajo épico a *@dest*',
'ptui directo a *@dest*',
'escupió a *@dest* y no se arrepiente',
'el escupitajo más legendario del chat fue para *@dest*',
 ],
 solo: [
'escupió al chat en general',
'ptui al vacío por las dudas',
'escupitajo sin víctima pero con mucha fuerza',
'escupió al viento porque puede',
'lanzó el escupitajo al grupo sin apuntar a nadie',
 ],
 },
 step: {
 emoji:'', nekos:'kick',
 mencion: [
'pisó a *@dest* con toda su fuerza',
'le pasó por encima a *@dest* literalmente',
'le puso el pie encima a *@dest* sin piedad',
'step on me — dijo *@dest*, y obedeció',
'le pisó el pie a *@dest* y ni se disculpó',
 ],
 solo: [
'pisó el suelo del chat con mucha actitud',
'anda pisando fuerte por el grupo',
'cada paso suyo se escucha desde lejos',
'pisotea el aire con estilo',
'step step step sin nadie debajo',
 ],
 },
 pisar: {
 emoji:'', nekos:'kick',
 mencion: [
'pisó a *@dest* sin ningún remordimiento',
'le pasó por encima a *@dest* tranquilamente',
'dejó la huella de su zapato en *@dest*',
'pisó a *@dest* como si fuera alfombra',
'le aplastó el pie a *@dest* y siguió su camino',
 ],
 solo: [
'pisa fuerte en el chat',
'cada pisada suya retumba en el grupo',
'camina pisando fuerte por el chat',
'pisó el suelo con toda la actitud',
'paso a paso, nadie lo/la detiene',
 ],
 },
 walk: {
 emoji:'', nekos:'walk',
 mencion: [
'está caminando tranquilamente con *@dest*',
'se fue a dar un paseo con *@dest*',
'caminó sin prisa junto a *@dest*',
'paseó a *@dest* por el chat con calma',
'anduvieron juntos/as sin decir nada',
 ],
 solo: [
'está caminando solo/a por el chat',
'se fue a pasear sin decir adónde',
'camina tranquilamente por el grupo',
'paseíto solitario sin compañía',
'walk walk walk por el chat sin rumbo',
 ],
 },
 caminar: {
 emoji:'', nekos:'walk',
 mencion: [
'caminó junto a *@dest* sin apuro',
'se fue a dar una vuelta con *@dest*',
'paseo tranquilo en compañía de *@dest*',
'anduvo al lado de *@dest* disfrutando el momento',
'caminata lenta y agradable con *@dest*',
 ],
 solo: [
'se puso a caminar solo/a por el chat',
'caminata solitaria sin destino concreto',
'anda por el grupo sin rumbo fijo',
'paseo sin compañía pero con actitud',
'camina tranquilo/a sin importar nada',
 ],
 },
 smile: {
 emoji:'', nekos:'smile',
 mencion: [
'le regaló la sonrisa más bonita a *@dest*',
'no pudo evitar sonreírle a *@dest*',
'le dedicó la mejor sonrisa del chat a *@dest*',
'se le dibujó una sonrisa enorme al ver a *@dest*',
'sonrió de oreja a oreja gracias a *@dest*',
 ],
 solo: [
'está sonriendo sin que nadie sepa por qué',
'la sonrisa no se le borra del chat',
'sonríe al vacío con mucho estilo',
'modo sonrisa: activado permanentemente',
'anda con una sonrisa que lo/la delata',
 ],
 },
 sonreir: {
 emoji:'', nekos:'smile',
 mencion: [
'le sonrió a *@dest* con todo el corazón',
'no puede dejar de sonreírle a *@dest*',
'una sonrisa enorme para *@dest*',
'se iluminó el chat cuando sonrió a *@dest*',
'la sonrisa más dulce del grupo fue para *@dest*',
 ],
 solo: [
'sonríe solo/a porque tiene sus razones',
'anda sonriendo por el chat y no cuenta por qué',
'la sonrisa de hoy no tiene explicación lógica',
'modo feliz y sonriente: ON',
'sonrisa eterna en el chat, alguien le hizo algo lindo',
 ],
 },
 smug: {
 emoji:'', nekos:'smug',
 mencion: [
'le lanzó la mirada más smug del universo a *@dest*',
'se siente muy superior a *@dest* y lo demuestra',
'esa sonrisita dice todo lo que piensa de *@dest*',
'mirada de"ya te lo dije"directo a *@dest*',
'el smug level de *@dest* está por el piso',
 ],
 solo: [
'está en modo smug y no se disculpa',
'esa sonrisita dice más de lo que parece',
'smug mode: activado sin necesidad de motivo',
'la cara de yo-lo-sabía más épica del chat',
'presumiendo de existir con esa mirada satisfecha',
 ],
 },
 presumir: {
 emoji:'', nekos:'smug',
 mencion: [
'está presumiendo delante de *@dest* descaradamente',
'le restregó su éxito en la cara a *@dest*',
'sonrió de lado mirando a *@dest* con suficiencia',
'presumió tanto que *@dest* ya no aguanta más',
'la mirada de superioridad va directa a *@dest*',
 ],
 solo: [
'está presumiendo al chat entero',
'modo presunción total: nadie lo/la para',
'el ego lo/la tiene flotando en el grupo',
'presume sin audiencia pero con mucha actitud',
'anda por el chat como el/la dueño/a del lugar',
 ],
 },
 cringe: {
 emoji:'', nekos:'cringe',
 mencion: [
'siente un cringe brutal por lo que hizo *@dest*',
'le sobrevino el cringe más grande del chat por *@dest*',
'no puede mirar lo que hace *@dest* sin cringear',
'el segundo-hand embarrassment de *@dest* lo/la mató',
'cringe máximo gracias a *@dest*',
 ],
 solo: [
'está cringando solo/a por algo del chat',
'el cringe lo/la tiene paralizado/a',
'second-hand embarrassment sin destinatario',
'se contrae de cringe sin poder evitarlo',
'cringe level: astronómico en el grupo hoy',
 ],
 },
 avergonzarse: {
 emoji:'', nekos:'cringe',
 mencion: [
'siente vergüenza ajena por lo que hizo *@dest*',
'no puede creer lo que acaba de hacer *@dest*',
'se encoge de vergüenza cada vez que *@dest* habla',
'la vergüenza ajena de *@dest* lo/la aplasta',
'ay *@dest*... por favor...',
 ],
 solo: [
'se muere de vergüenza ajena en el chat',
'vergüenza modo máximo activado',
'anda con cringe acumulado de todo el día',
'no puede con el nivel de vergüenza ajena',
'todo el chat le da cringe hoy sin excepción',
 ],
 },
 highfive: {
 emoji:'', nekos:'highfive',
 mencion: [
'le chocó los cinco a *@dest* con mucha fuerza',
'high five épico con *@dest* que se oyó en todo el chat',
'no dudó en chocar los cinco con *@dest*',
'extendió la mano y *@dest* no lo/la dejó esperando',
'el high five más sonoro del grupo fue con *@dest*',
 ],
 solo: [
'chocó los cinco al aire esperando que alguien responda',
'tiene la mano lista para un high five y nadie aparece',
'high five solitario en el chat',
'palma extendida, nadie la chocó',
'se chocó los cinco con la pared porque nadie estaba',
 ],
 },
 bullying: {
 emoji:'', nekos:'bully',
 mencion: [
'le está haciendo bullying a *@dest* sin piedad',
'molestó a *@dest* hasta que reaccionó',
'eligió a *@dest* como víctima del día',
'no para de molestar a *@dest* y lo disfruta',
'el blanco de hoy es *@dest* y no hay escape',
 ],
 solo: [
'busca a quién hacerle bullying en el grupo',
'modo bully activado, nadie está a salvo',
'anda molestando al que se le acerque',
'tiene energía de sobra para hacer de las suyas',
'el bully del chat entró al modo activo',
 ],
 },
 bully: {
 emoji:'', nekos:'bully',
 mencion: [
'está buleando a *@dest* en plena vista de todos',
'eligió a *@dest* para su show de bullying hoy',
'le metió el dedo en el ojo a *@dest* verbalmente',
'no hay quien pare el bully que le mete a *@dest*',
'todo el grupo vio cómo le hizo bullying a *@dest*',
 ],
 solo: [
'busca víctima en el grupo, nadie está seguro',
'anda de bully y nadie lo/la detiene',
'el bully nivel 100 se manifiesta en el chat',
'modo intimidación: activado sin target por ahora',
'tiene ganas de molestar a alguien del grupo',
 ],
 },
 preg: {
 emoji:'', nekos:'hug',
 mencion: [
'de algún modo misterioso dejó embarazada a *@dest*',
'nueve meses después, *@dest* tiene algo que contar',
'la cigüeña llegó a casa de *@dest* y señala a alguien',
'la historia de *@dest* y el embarazo misterioso empieza aquí',
'*@dest* y el/ella: padres/madres sin explicación lógica',
 ],
 solo: [
'apareció embarazado/a y nadie sabe cómo',
'la cigüeña llegó sin que nadie la invitara',
'está esperando un bebé de circunstancias misteriosas',
'nueve meses, sin explicaciones, sin preguntas',
'el embarazo más inesperado del chat oficial',
 ],
 },
 preñar: {
 emoji:'', nekos:'hug',
 mencion: [
'de alguna forma inexplicable preñó a *@dest*',
'la cigüeña apunta a *@dest* y no hay defensa posible',
'el embarazo de *@dest* tiene un responsable misterioso',
'nueve meses de espera para *@dest*, gracias a este/esta',
'preñó a *@dest* sin que nadie lo/la vea venir',
 ],
 solo: [
'anda preñando a quien se descuide',
'la cigüeña sale de su boca y no se sabe a dónde va',
'energía de padre/madre irresponsable en el chat',
'modo preñar: activado sin víctima confirmada',
'el historial del grupo dice que algo raro va a pasar',
 ],
 },
 peek: {
 emoji:'', nekos:'peek',
 mencion: [
'está espiando a *@dest* desde detrás de la puerta',
'se asomó sigilosamente para ver qué hace *@dest*',
'no puede resistirse a echar un vistazo a *@dest*',
'observa a *@dest* en secreto sin que lo sepa',
 ],
 solo: [
'está espiando detrás de una puerta por diversión',
'se asomó al chat con mucha discreción',
'anda mirando de reojos sin que nadie lo note',
'modo espía activado, alguien será observado',
 ],
 },
 comfort: {
 emoji:'', nekos:'comfort',
 mencion: [
'está consolando a *@dest* con mucho cariño',
'se acercó a *@dest* para darle ánimos',
'le ofreció su hombro a *@dest* para que llore',
'hizo sentir mejor a *@dest* con su presencia',
 ],
 solo: [
'se está consolando a sí mismo/a con dignidad',
'anda buscando a alguien que necesite consuelo',
'modo consuelo activado, ¿quién lo necesita?',
'reparte palabras de aliento a quien las quiera',
 ],
 },
 thinkhard: {
 emoji:'', nekos:'thinkhard',
 mencion: [
'está pensando muy profundo en *@dest*',
'no puede dejar de reflexionar sobre *@dest*',
'se quedó con la mente en blanco pensando en *@dest*',
'la situación de *@dest* lo/la tiene en modo análisis',
 ],
 solo: [
'se quedó pensando muy intensamente',
'el cerebro está a mil revoluciones ahora mismo',
'modo pensamiento profundo: activado al máximo',
'está procesando algo que el chat no entiende',
 ],
 },
 curious: {
 emoji:'', nekos:'curious',
 mencion: [
'está muy curioso/a por lo que hace *@dest*',
'no puede dejar de preguntarse sobre *@dest*',
'la curiosidad por *@dest* lo/la está matando',
'siente la necesidad de investigar a *@dest*',
 ],
 solo: [
'se muestra curioso/a por todo lo del chat',
'anda haciendo preguntas que nadie responde',
'la curiosidad lo/la tiene en modo detective',
'quiere saber más y no para de explorar',
 ],
 },
 sniff: {
 emoji:'', nekos:'sniff',
 mencion: [
'le olfateó el cuello a *@dest* sin avisar',
'olió a *@dest* y dice que huele muy bien',
'se acercó mucho a *@dest* para inhalar profundo',
'el olfato de *@dest* lo/la tiene fascinado/a',
 ],
 solo: [
'se olfatea como si buscara algo raro',
'anda oliendo el ambiente del chat',
'inhala el aroma del grupo con satisfacción',
'modo sabueso activado, todo tiene un olor distinto',
 ],
 },
 trip: {
 emoji:'', nekos:'trip',
 mencion: [
'tropezó accidentalmente con *@dest* y los dos cayeron',
'se fue de bruces por culpa de *@dest*',
'su pie encontró el pie de *@dest* y el resto es historia',
'tropezó con *@dest* y fue el caos más gracioso del día',
 ],
 solo: [
'se tropezó consigo mismo/a, otra vez',
'tropezó sin razón y sin testigos... o eso cree',
'el piso del chat tiene trampa y lo comprobó',
'cayó de la nada y no sabe bien por qué',
 ],
 },
 blowkiss: {
 emoji:'', nekos:'blowkiss',
 mencion: [
'le lanzó un besito volado a *@dest*',
'mandó el beso más tierno del chat directo a *@dest*',
'sopló un beso con toda la ternura hacia *@dest*',
'el besito voló hasta llegar a las mejillas de *@dest*',
 ],
 solo: [
'se manda un beso al espejo y luce genial',
'lanzó un besito al aire para quien lo quiera atrapar',
'beso volado para todo el grupo sin excepción',
'manda amor en forma de besito sin destinatario',
 ],
 },
 snuggle: {
 emoji:'', nekos:'snuggle',
 mencion: [
'se acurrucó dulcemente con *@dest*',
'se pegó a *@dest* como una almohada tibia',
'no hay quien separe este snuggle de *@dest*',
'encontró en *@dest* el lugar más cómodo del chat',
 ],
 solo: [
'se acurruca con una almohada suave en el chat',
'modo snuggle solitario pero muy cómodo',
'busca a alguien con quien acurrucarse urgente',
'se hizo bolita esperando compañía del grupo',
 ],
 },
 push: {
 emoji:'', nekos:'push',
 mencion: [
'empujó a *@dest* de golpe sin avisar',
'le dio un empujón a *@dest* con mucha fuerza',
'*@dest* salió volando por el empujón que recibió',
'no le gustó lo que hizo *@dest* y lo/la empujó',
 ],
 solo: [
'se empujó a sí mismo/a y voló un momento',
'anda empujando el aire con frustración',
'modo empujón: activado sin objetivo por ahora',
'tiene ganas de empujar a alguien del grupo',
 ],
 },
 nope: {
 emoji:'', nekos:'nope',
 mencion: [
'le dijo "¡No!" rotundamente a *@dest*',
'negó con toda la cabeza lo que propuso *@dest*',
'el nope más categórico del chat fue para *@dest*',
'rechazó la idea de *@dest* sin contemplaciones',
 ],
 solo: [
'expresa claramente su desacuerdo con todo',
'modo nope activado: nada ni nadie convence',
'nope al chat entero, no hay más que hablar',
'negación total y sin posibilidad de diálogo',
 ],
 },
 jump: {
 emoji:'', nekos:'jump',
 mencion: [
'saltó de felicidad junto a *@dest*',
'dio el salto más alto del chat emocionado/a por *@dest*',
'no puede quedarse quieto/a al lado de *@dest*',
'saltó hacia *@dest* con toda la emoción del mundo',
 ],
 solo: [
'salta de felicidad sin motivo aparente',
'el salto de alegría más inesperado del chat',
'modo salto: activado por algo que nadie vio',
'rebota por el chat de pura energía positiva',
 ],
 },
 call: {
 emoji:'', nekos:'call',
 mencion: [
'llamó al número de *@dest* para hablar con urgencia',
'marcó el teléfono de *@dest* sin parar',
'dejó 47 llamadas perdidas a *@dest* en el chat',
'la llamada de *@dest* fue directamente al buzón',
 ],
 solo: [
'marca su propio número esperando respuesta',
'llama al vacío porque necesita hablar con alguien',
'modo llamada: conectado/a pero sin respuesta',
'tiene el teléfono en la oreja y nadie contesta',
 ],
 },
 impregnate: {
 emoji:'', nekos:'impregnate',
 mencion: [
'de algún modo misterioso dejó embarazada a *@dest*',
'la cigüeña llegó a casa de *@dest* y señala a este/esta',
'*@dest* va a necesitar nueve meses para explicar esto',
'el embarazo de *@dest* tiene un responsable en el chat',
 ],
 solo: [
'apareció embarazado/a y nadie sabe cómo ni cuándo',
'la cigüeña llegó sin que nadie la invitara',
'nueve meses por delante, sin explicaciones',
'el embarazo más inesperado del chat es una realidad',
 ],
 },
 embarazar: {
 emoji:'', nekos:'impregnate',
 mencion: [
'embarazó a *@dest* de la forma más misteriosa',
'la cigüeña apunta directamente a *@dest*',
'alguien tiene que darle la noticia a *@dest*',
'misteriosamente *@dest* espera familia gracias a este/esta',
 ],
 solo: [
'anda embarazando gente sin que nadie lo entienda',
'la cigüeña le sigue los pasos a donde va',
'modo cigüeña caótica: activado en el grupo',
'el caos reproductivo del chat tiene un nombre',
 ],
 },
};

module.exports = { SFW_ACCIONES };
